### ISSUE TITLE
Can't auth since update

### ISSUE THREAD

**Issue by pablojimeno** [fniephaus/alfred-dropbox#5]
Hello Fabio, I had the workflow installed and authorised and after updating to 2.2 version it doesn't work anymore. I deleted the keychain, and the auth from dropbox, but can't authorise it again.

This is the debugger log:

```[2017-09-01 19:17:06][ERROR: input.scriptfilter] Code 1: 19:17:05 workflow.py:2225 DEBUG    Workflow version : 2.2.0
19:17:05 workflow.py:1628 DEBUG    Reading settings from `/Users/pablo/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
19:17:05 workflow.py:2514 DEBUG    Update check not due
19:17:05 workflow.py:1859 DEBUG    Loading cached data from : /Users/pablo/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
19:17:05 workflow.py:2444 DEBUG    update_data : {u'available': True, u'version': u'v2.2', u'download_url': u'https://github.com/fniephaus/alfred-dropbox/releases/download/v2.2/Dropbox-Client-for-Alfred.alfredworkflow'}
19:17:05 workflow.py:2243 ERROR    'Workflow' object has no attribute 'update_info'
Traceback (most recent call last):
  File "/Users/pablo/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.602B4993-EECA-480F-B1CB-964C0C5A5129/workflow/workflow.py", line 2236, in run
    func(self)
  File "dropbox_filter.py", line 16, in main
    subtitle = 'New: %s' % wf.update_info['body']
AttributeError: 'Workflow' object has no attribute 'update_info'
19:17:05 workflow.py:2246 INFO     For assistance, see: https://github.com/fniephaus/alfred-dropbox/issues
19:17:05 workflow.py:2267 DEBUG    Workflow finished in 0.014 seconds.```

**Comment by fniephaus** [comment]
Please update to v2.3 manually and reopen the issue if the problem persists.
